
on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: mawinkler/python-lint-action
        with:
          # python-root-list: "python_alelo tests"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "code/*.py --fail-under=8"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""